### ISSUE TITLE
screenshot of SL's early/late histogram

### ISSUE THREAD

**Issue by quietly-turning** [geefr/stepmania-linux-goodies#3]
In the Wiki page on *So You Think You Have Polling Issues*, you write:
> TODO: Nice screenshot of main graph, with big/separate spikes

I'm [unable to submit a pull request](https://stackoverflow.com/a/11481887) to a GitHub Wiki, so here's a nice screenshot of SL's early/late histogram, with clearly delineated spikes.  Feel free to use it in your Wiki page.

![screenshot](https://i.imgur.com/oMAQKoM.jpg)

URL: https://i.imgur.com/oMAQKoM.jpg

**Comment by geefr** [comment]
Oh hey thanks, I'd completely forgotten about that...Not having PRs sounds like a pretty big flaw :/

If you'd like access to the repo let me know, no problem in granting it

Either way that's updated now, thanks again.
